<!DOCTYPE html>
<html lang="en">
<head>
    <?php require 'userHead.php'?>    
</head>
<body>
    <?php require 'userNav.php'?>

    <div class="my-20 px-16">
        <h1 class="text-center font-bold text-4xl mb-5">PRIVACY POLICY</h1>
        <p>
            <span class="font-bold">Effective date: 2024-12-11</span><br><br>
            1. <b>Introduction</b><br>
            Welcome to <b>RideHub Service (R.H.S.) Corporation</b>.<br>
            <b>RideHub Service (R.H.S.)</b> Corporation (“us”, “we”, or “our”) operates <b>www.ridehub.com</b> (hereinafter referred to as <b>“Service”</b>).<br>
            Our Privacy Policy governs your visit to <b>www.ridehub.com</b>, and explains how we collect, safeguard and disclose information that results from your use of our Service.<br>
            We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our 
            Terms and Conditions. Our Terms and Conditions (<b>“Terms”</b>) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (<b>“Agreement”</b>).<br><br>

            2. <b>Definitions</b><br>
            <b>SERVICE</b> means the www.anistransport.com website operated by Anis Trans Service (A.T.S.) Corporation. <br>
            <b>PERSONAL DATA</b> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession). <br>
            <b>USAGE DATA</b> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit). <br>
            <b>COOKIES</b> are small files stored on your device (computer or mobile device). <br>
            <b>DATA CONTROLLER</b> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a
            Data Controller of your data. <br>
            <b>DATA PROCESSORS</b> (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively. <br>
            <b>DATA SUBJECT</b> is any living individual who is the subject of Personal Data. <br>
            <b>THE USER</b> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data. <br><br>

            3. <b>Information Collection and Use</b><br>
            We collect several different types of information for various purposes to provide and improve our Service to you. <br><br>

            4. <b>Types of Data Collected</b><br>
            <b>Personal Data</b>
            While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (<b>“Personal Data”</b>). Personally identifiable information may include, but is not limited to: <br>
            0.1. Email address <br>
            0.2. First name and last name<br>
            0.3. Phone number<br>
            0.4. Address, Country, State, Province, ZIP/Postal code, City<br>
            0.5. Cookies and Usage Data<br>
            We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.<br><br>
            <b>Usage Data</b> <br>
            We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (<b>“Usage Data”</b>).<br>
            This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers
            and other diagnostic data.<br>
            When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and
            other diagnostic data.<br><br>

            <b>Location Data</b> <br>
            We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service.<br>
            You can enable or disable location services when you use our Service at any time by way of your device settings.<br><br>
            <b>Tracking Cookies Data</b> <br>
            We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.<br>
            Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track
            information and to improve and analyze our Service.<br>
            You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.<br>
            Examples of Cookies we use:<br>
            0.1. <b>Session Cookies</b>: We use Session Cookies to operate our Service.<br>
            0.2. <b>Preference Cookies</b>: We use Preference Cookies to remember your preferences and various settings.<br>
            0.3. <b>Security Cookies</b>: We use Security Cookies for security purposes.<br>
            0.4. <b>Advertising Cookies</b>: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.<br><br>
            <b>Other Data</b> <br>
            While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification,
            professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.<br><br>
            5. <b>Use of Data</b> <br>
            Anis Trans Service (A.T.S.) Corporation uses the collected data for various purposes:<br>
            0.1. to provide and maintain our Service;<br>
            0.2. to notify you about changes to our Service;<br>
            0.3. to allow you to participate in interactive features of our Service when you choose to do so;<br>
        </p>
    </div>
</body>
<script>
    const dropdownButton = document.getElementById('dropdownButton');
    const dropdownMenu = document.getElementById('dropdownMenu');

    dropdownButton.addEventListener('click', () => {
      dropdownMenu.classList.toggle('hidden');
    });
</script>
<script src="./public/lib/js/script.js"></script>
</html>